class MathDisplayValues:
    SQUARE_LEN = 120 # Sideview length of scintillator in unit x
    SCINTILLATOR_THICKNESS = 10
    SPACE_BETWEEN_SCINTILLATORS = 2
    SPACE_BETWEEN_STRUCTURES = 162
    NUM_SCINTILLATOR_XY_PER_STRUCTURE = 3
    NUM_SCINTILLATORS_PER_STRUCTURE = 2 * NUM_SCINTILLATOR_XY_PER_STRUCTURE
    NUM_SMALL_SPACES = NUM_SCINTILLATORS_PER_STRUCTURE - 1