class GlfwRenderer:
    def __init__(self, window, attach_callbacks=False):
        ...

    def process_inputs(self):
        ...

    def render(self, draw_data):
        ...

    def keyboard_callback(self, *args, **kwargs):
        ...
    
    def char_callback(self, *args, **kwargs):
        ...
